# Cloudflare Pages 配置
name = "mgx-edgeone"
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]

# 指定构建输出目录
pages_build_output_dir = ".next"

[build]
command = "npx @cloudflare/next-on-pages@1"
