# Cloudflare Pages 配置
name = "mgx-edgeone"
compatibility_date = "2023-10-30"
node_compat = true
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm install && npm run build"

[build.upload]
format = "directory"
dir = ".next"

[site]
bucket = ".next"
