# Cloudflare Pages 配置
[build]
command = "npm install && npm run build"
node_version = "22"

[build.environment]
NODE_VERSION = "22"

[build.upload]
format = "directory"
dir = ".next"

[site]
bucket = ".next"

# 启用 Node.js 兼容性
compatibility_flags = ["nodejs_compat"]
