# Cloudflare Pages 配置
[build]
command = "npm install && npm run build"

[site]
bucket = ".next"

# 启用 Node.js 兼容性
[compatibility_flags]
nodejs_compat = true

# 指定输出目录
[build.upload]
format = "directory"
dir = ".next"
